server:
  port: 8501

spcloud:
  cassandra:
    contact:
      point: 127.0.0.1
    port: 9042
    keyspace:
      name: springcloud

    username: cassandra
    password: cassandra

spring:
  application: account-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/